services:

  redis:
    image: redis:7
    container_name: chat_application_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: chat_application_web
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  daphne:
    build: .
    container_name: chat_application_daphne
    command: daphne -b 0.0.0.0 -p 8001 chat_application.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - redis